version: '3'
services:
  sakila-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: sakila
      MYSQL_DATABASE: sakila
      MYSQL_PASSWORD: sakila
      TZ: Asia/Tokyo
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - sakilastore:/var/lib/mysql
      - ../sakila-db/sakila-schema.sql:/docker-entrypoint-initdb.d/1_sakila-schema.sql
      - ../sakila-db/sakila-data.sql:/docker-entrypoint-initdb.d/2_sakila-data.sql
    ports:
      - "3306:3306"
    container_name: sakila-mysql

volumes:
  sakilastore:
    driver: local

