version: "3"
services:
  sakila-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - sakilastore:/var/lib/mysql
      - ../employee-db/:/tmp
      - ../employee-db/employees.sql:/docker-entrypoint-initdb.d/1_employees.sql
    ports:
      - "3306:3306"
    container_name: sakila-mysql

volumes:
  sakilastore:
    driver: local
